// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using impoTrack.Data;

#nullable disable

namespace impoTrack.Entities
{
    [DbContext(typeof(impoTrackContext))]
    partial class impoTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("impoTrack.Models.Entrega", b =>
                {
                    b.Property<int>("EntregaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntregaID"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PedidoID")
                        .HasColumnType("integer");

                    b.Property<int?>("RepartidorID")
                        .HasColumnType("integer");

                    b.Property<string>("RutaEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZonaEntrega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EntregaID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("RepartidorID");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("impoTrack.Models.Informe", b =>
                {
                    b.Property<int>("InformeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InformeID"));

                    b.Property<string>("DatosInforme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoInforme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("InformeID");

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("impoTrack.Models.Notificacion", b =>
                {
                    b.Property<int>("NotificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificacionID"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PedidoID")
                        .HasColumnType("integer");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("integer");

                    b.HasKey("NotificacionID");

                    b.HasIndex("PedidoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("impoTrack.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedidoID"));

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FechaEntregaEstimada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FechaPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductoID")
                        .HasColumnType("integer");

                    b.Property<int>("RepartidorID")
                        .HasColumnType("integer");

                    b.HasKey("PedidoID");

                    b.HasIndex("ProductoID");

                    b.HasIndex("RepartidorID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("impoTrack.Models.ProblemaEntrega", b =>
                {
                    b.Property<int>("ProblemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProblemaID"));

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoProblema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PedidoID")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProblemaID");

                    b.HasIndex("PedidoID");

                    b.ToTable("ProblemasEntrega");
                });

            modelBuilder.Entity("impoTrack.Models.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductoID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductoID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("impoTrack.Models.Repartidor", b =>
                {
                    b.Property<int>("RepartidorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RepartidorID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UbicacionActual")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RepartidorID");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("impoTrack.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("impoTrack.Models.Entrega", b =>
                {
                    b.HasOne("impoTrack.Models.Pedido", "Pedido")
                        .WithMany("Entregas")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("impoTrack.Models.Repartidor", "Repartidor")
                        .WithMany("Entregas")
                        .HasForeignKey("RepartidorID");

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("impoTrack.Models.Notificacion", b =>
                {
                    b.HasOne("impoTrack.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoID");

                    b.HasOne("impoTrack.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("impoTrack.Models.Pedido", b =>
                {
                    b.HasOne("impoTrack.Models.Producto", "Producto")
                        .WithMany("Pedidos")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("impoTrack.Models.Repartidor", "Repartidor")
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("impoTrack.Models.ProblemaEntrega", b =>
                {
                    b.HasOne("impoTrack.Models.Pedido", "Pedido")
                        .WithMany("ProblemasEntrega")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("impoTrack.Models.Pedido", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("ProblemasEntrega");
                });

            modelBuilder.Entity("impoTrack.Models.Producto", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("impoTrack.Models.Repartidor", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("impoTrack.Models.Usuario", b =>
                {
                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
